
currentLine = function() {
  return Router.current().params.line;
};

currentTransitType = function() {
  return Router.current().params.type;
};

currentStations = function () {
  return stations[currentLine()];
};

listOfLines = function() {
  return {
    subway: [
      {
        line: "Market-Frankford Line",
        color: "blue-line",
        type: "subway",
        directions: [
          {direction: "Westbound (to 69th Street Transportation Ctr.)", path: "Market-Frankford Line - Westbound"},
          {direction: "Eastbound (to Frankford Trans. Ctr.)", path: "Market-Frankford Line - Eastbound"}
        ]
      },
      {
        line: "Broad Street Line",
        color: "orange-line",
        type: "subway",
        directions: [
          {direction: "Northbound (to Fern Rock Transportation Ctr.)", path: "Broad Street Line - Northbound"},
          {direction: "Southbound (to AT&T Station)", path: "Broad Street Line - Southbound"}
        ]
      },
      {
        line: "Trolleys",
        color: "green-line",
        type: "subway",
        directions: [
          {direction: "10 - Westbound (to Overbrook)", path: "Route 10 - Westbound"},
          {direction: "10 - Eastbound (to Center City)", path: "Route 10 - Eastbound"},
          {direction: "11 - Westbound (to Darby)", path: "Route 11 - Westbound"},
          {direction: "11 - Eastbound (to Center City)", path: "Route 11 - Eastbound"},
          {direction: "13 - Westbound (to Yeadon)", path: "Route 13 - Westbound"},
          {direction: "13 - Eastbound (to Center City)", path: "Route 13 - Eastbound"},
          {direction: "34 - Westbound (to Angora)", path: "Route 34 - Westbound"},
          {direction: "101 - Eastbound (to 69th Street Transportation Center)", path: "Route 101 - Eastbound"},
          {direction: "101 - Westbound (to Media)", path: "Route 101 - Westbound"},
          {direction: "102 - Eastbound (to 69th Street Transportation Center)", path: "Route 102 - Westbound"},
          {direction: "102 - Westbound (to Sharon Hill)", path: "Route 102 - Westbound"},
        ]
      },
      {
        line: "PATCO Speedline",
        color: "red-line",
        type: "subway",
        directions: [
          {direction: "Westbound (to 15th & Locust)", path: "PATCO Speedline - Westbound"},
          {direction: "Eastbound (to Lindenwold)", path: "PATCO Speedline - Eastbound"}
        ]
      },
      {
        line: "Norristown High Speed Line",
        color: "purple-line",
        type: "subway",
        directions: [
          {direction: "Inbound (to 69th St)", path: "Norristown High Speed Line - Inbound"},
          {direction: "Outbound (to Norristown)", path: "Norristown High Speed Line - Outbound"}
        ]
      }
    ],
    train: [
      {
        line: "Airport Line",
        color: "silver-line",
        type: "train",
        directions: [
          {direction: "Inbound (to Philadelphia)", path: "Airport Line - Inbound"},
          {direction: "Outbound (to Airport)", path: "Airport Line - Outbound"}
        ]
      },
      {
        line: "Chestnut Hill East Line",
        color: "silver-line",
        type: "train",
        directions: [
          {direction: "Inbound (to Philadelphia)", path: "Chestnut Hill East Line - Inbound"},
          {direction: "Outbound (to Chestnut Hill East)", path: "Chestnut Hill East Line - Outbound"}
        ]
      },
      {
        line: "Chestnut Hill West Line",
        color: "silver-line",
        type: "train",
        directions: [
          {direction: "Inbound (to Philadelphia)", path: "Chestnut Hill West Line - Inbound"},
          {direction: "Outbound (to Chestnut Hill West)", path: "Chestnut Hill West Line - Outbound"}
        ]
      },
      {
        line: "Cynwyd Line",
        color: "silver-line",
        type: "train",
        directions: [
          {direction: "Inbound (to Philadelphia)", path: "Cynwyd Line - Inbound"},
          {direction: "Outbound (to Cynwyd)", path: "Cynwyd Line - Outbound"}
        ]
      },
      {
        line: "Fox Chase Line",
        color: "silver-line",
        type: "train",
        directions: [
          {direction: "Inbound (to Philadelphia)", path: "Fox Chase Line - Inbound"},
          {direction: "Outbound (to Fox Chase)", path: "Fox Chase Line - Outbound"}
        ]
      },
      {
        line: "Lansdale-Doylestown Line",
        color: "silver-line",
        type: "train",
        directions: [
          {direction: "Inbound (to Philadelphia)", path: "Lansdale-Doylestown Line - Inbound"},
          {direction: "Outbound (to Lansdale-Doylestown)", path: "Lansdale-Doylestown Line - Outbound"}
        ]
      },
      {
        line: "Manayunk-Norristown Line",
        color: "silver-line",
        type: "train",
        directions: [
          {direction: "Inbound (to Philadelphia)", path: "Manayunk-Norristown Line - Inbound"},
          {direction: "Outbound (to Manayunk-Norristown)", path: "Manayunk-Norristown Line - Outbound"}
        ]
      },
      {
        line: "Media-Elwyn Line",
        color: "silver-line",
        type: "train",
        directions: [
          {direction: "Inbound (to Philadelphia)", path: "Media-Elwyn Line - Inbound"},
          {direction: "Outbound (to Media-Elwyn)", path: "Media-Elwyn Line - Outbound"}
        ]
      },
      {
        line: "Paoli-Thorndale Line",
        color: "silver-line",
        type: "train",
        directions: [
          {direction: "Inbound (to Philadelphia)", path: "Paoli-Thorndale Line - Inbound"},
          {direction: "Outbound (to Paoli-Thorndale)", path: "Paoli-Thorndale Line - Outbound"}
        ]
      },
      {
        line: "Trenton Line",
        color: "silver-line",
        type: "train",
        directions: [
          {direction: "Inbound (to Philadelphia)", path: "Trenton Line - Inbound"},
          {direction: "Outbound (to Trenton)", path: "Trenton Line - Outbound"}
        ]
      },
      {
        line: "Warminster Line",
        color: "silver-line",
        type: "train",
        directions: [
          {direction: "Inbound (to Philadelphia)", path: "Warminster Line - Inbound"},
          {direction: "Outbound (to Warminster)", path: "Warminster Line - Outbound"}
        ]
      },
      {
        line: "West Trenton Line",
        color: "silver-line",
        type: "train",
        directions: [
          {direction: "Inbound (to Philadelphia)", path: "West Trenton Line - Inbound"},
          {direction: "Outbound (to West Trenton)", path: "West Trenton Line - Outbound"}
        ]
      },
      {
        line: "Wilmington-Newark Line",
        color: "silver-line",
        type: "train",
        directions: [
          {direction: "Inbound (to Philadelphia)", path: "Wilmington-Newark Line - Inbound"},
          {direction: "Outbound (to Wilmington-Newark)", path: "Wilmington-Newark Line - Outbound"}
        ]
      },
    ]
  };
};

stations = {
  'Market-Frankford Line - Westbound': [
    {name: 'Frankford Trans. Ctr.'},
    {name: 'Arrott Transportation Center'},
    {name: 'Church'},
    {name: 'Erie-Torresdale'},
    {name: 'Tioga'},
    {name: 'Allegheny'},
    {name: 'Somerset'},
    {name: 'Huntingdon'},
    {name: 'York-Dauphin'},
    {name: 'Berks'},
    {name: 'Girard'},
    {name: 'Spring Garden'},
    {name: '2nd Street'},
    {name: '5th Street'},
    {name: '8th Street'},
    {name: '11th Street'},
    {name: '13th Street'},
    {name: '15th Street'},
    {name: '30th Street'},
    {name: '34th Street'},
    {name: '40th Street'},
    {name: '46th Street'},
    {name: '52nd Street'},
    {name: '56th Street'},
    {name: '60th Street'},
    {name: '63rd Street'},
    {name: 'Millbourne'},
    {name: '69th Street Transportation Ctr.'}
  ],
  'Market-Frankford Line - Eastbound': [
    {name: '69th Street Transportation Ctr.'},
    {name: 'Millbourne'},
    {name: '63rd Street'},
    {name: '60th Street'},
    {name: '56th Street'},
    {name: '52nd Street'},
    {name: '46th Street'},
    {name: '40th Street'},
    {name: '34th Street'},
    {name: '30th Street'},
    {name: '15th Street'},
    {name: '13th Street'},
    {name: '11th Street'},
    {name: '8th Street'},
    {name: '5th Street'},
    {name: '2nd Street'},
    {name: 'Spring Garden'},
    {name: 'Girard'},
    {name: 'Berks'},
    {name: 'York-Dauphin'},
    {name: 'Huntingdon'},
    {name: 'Somerset'},
    {name: 'Allegheny'},
    {name: 'Tioga'},
    {name: 'Erie-Torresdale'},
    {name: 'Church'},
    {name: 'Arrott Transportation Center'},
    {name: 'Frankford Trans. Ctr.'}
  ],
  'Broad Street Line - Northbound': [
    {name: 'AT&T Station'},
    {name: 'Oregon'},
    {name: 'Snyder'},
    {name: 'Tasker-Morris'},
    {name: 'Ellsworth-Federal'},
    {name: 'Lombard-South'},
    {name: 'Walnut-Locust'},
    {name: 'City Hall'},
    {name: 'Race-Vine'},
    {name: 'Spring Garden'},
    {name: 'Fairmount'},
    {name: 'Girard'},
    {name: 'Cecil B. Moore'},
    {name: 'Susquehanna-Dauphin'},
    {name: 'North Philadelphia'},
    {name: 'Allegheny'},
    {name: 'Erie'},
    {name: 'Hunting Park'},
    {name: 'Wyoming'},
    {name: 'Logan'},
    {name: 'Olney Transportation Ctr.'},
    {name: 'Fern Rock Transportation Ctr.'}
  ],
  'Broad Street Line - Southbound': [
    {name: 'Fern Rock Transportation Ctr.'},
    {name: 'Olney Transportation Ctr.'},
    {name: 'Logan'},
    {name: 'Wyoming'},
    {name: 'Hunting Park'},
    {name: 'Erie'},
    {name: 'Allegheny'},
    {name: 'North Philadelphia'},
    {name: 'Susquehanna-Dauphin'},
    {name: 'Cecil B. Moore'},
    {name: 'Girard'},
    {name: 'Fairmount'},
    {name: 'Spring Garden'},
    {name: 'Race-Vine'},
    {name: 'City Hall'},
    {name: 'Walnut-Locust'},
    {name: 'Lombard-South'},
    {name: 'Ellsworth-Federal'},
    {name: 'Tasker-Morris'},
    {name: 'Snyder'},
    {name: 'Oregon'},
    {name: 'AT&T Station'}
  ],
  'PATCO Speedline - Westbound': [
    {name: 'Lindenwold'},
    {name: 'Ashland'},
    {name: 'Woodcrest'},
    {name: 'Haddonfield'},
    {name: 'Westmont'},
    {name: 'Collingswood'},
    {name: 'Ferry Avenue'},
    {name: 'Broadway'},
    {name: 'City Hall'},
    {name: '8th & Market St.'},
    {name: '9-10th & Locust'},
    {name: '12-13th & Locust'},
    {name: '15-16th & Locust'}
  ],
  'PATCO Speedline - Eastbound': [
    {name: '15-16th & Locust'},
    {name: '12-13th & Locust'},
    {name: '9-10th & Locust'},
    {name: '8th & Market St.'},
    {name: 'City Hall'},
    {name: 'Broadway'},
    {name: 'Ferry Avenue'},
    {name: 'Collingswood'},
    {name: 'Westmont'},
    {name: 'Haddonfield'},
    {name: 'Woodcrest'},
    {name: 'Ashland'},
    {name: 'Lindenwold'}
  ],
  'Route 10 - Westbound': [
    {name: '13th Street'},
    {name: '15th Street'},
    {name: '19th Street'},
    {name: '22nd Street'},
    {name: '30th Street'},
    {name: '33rd Street'},
    {name: '36th Street'},
    {name: 'Overbrook Loop'}
  ],
  'Route 10 - Eastbound': [
    {name: 'Overbrook Loop'},
    {name: '36th Street'},
    {name: '33rd Street'},
    {name: '30th Street'},
    {name: '22nd Street'},
    {name: '19th Street'},
    {name: '15th Street'},
    {name: '13th Street'}
  ],
  'Route 11 - Westbound': [
    {name: '13th Street'},
    {name: '15th Street'},
    {name: '19th Street'},
    {name: '22nd Street'},
    {name: '30th Street'}
  ],
  'Route 11 - Eastbound': [
    {name: '30th Street'},
    {name: '22nd Street'},
    {name: '19th Street'},
    {name: '15th Street'},
    {name: '13th Street'}
  ],
  'Route 13 - Westbound': [
    {name: '13th Street'},
    {name: '15th Street'},
    {name: '19th Street'},
    {name: '22nd Street'},
    {name: '30th Street'}
  ],
  'Route 13 - Eastbound': [
    {name: '30th Street'},
    {name: '22nd Street'},
    {name: '19th Street'},
    {name: '15th Street'},
    {name: '13th Street'}
  ],
  'Route 34 - Westbound': [
    {name: '13th Street'},
    {name: '15th Street'},
    {name: '19th Street'},
    {name: '22nd Street'},
    {name: '30th Street'}
  ],
  'Route 34 - Eastbound': [
    {name: '30th Street'},
    {name: '22nd Street'},
    {name: '19th Street'},
    {name: '15th Street'},
    {name: '13th Street'}
  ],
  'Route 101 - Westbound': [
    {name: 'Fairfield Avenue'},
    {name: 'Drexel Hill Junction'},
    {name: 'Springfield Road'},
    {name: 'Pine Ridge'},
    {name: 'Orange Street'}
  ],
  'Route 101 - Eastbound': [
    {name: 'Fairfield Avenue'},
    {name: 'Drexel Hill Junction'},
    {name: 'Springfield Road'},
    {name: 'Pine Ridge'},
    {name: 'Orange Street'}
  ],
   'Route 102 - Westbound': [
    {name: 'Fairfield Avenue'},
    {name: 'Drexel Hill Junction'},
    {name: 'Baltimore Avenue'},
    {name: 'Providence Road'},
    {name: 'MacDade Boulevard'}
  ],
  'Route 102 - Eastbound': [
   {name: 'Fairfield Avenue'},
    {name: 'Drexel Hill Junction'},
    {name: 'Baltimore Avenue'},
    {name: 'Providence Road'},
    {name: 'MacDade Boulevard'}
  ],
  'Airport Line - Inbound': [
    {name: 'Airport Terminal E F'},
    {name: 'Airport Terminal C D'},
    {name: 'Airport Terminal B'},
    {name: 'Airport Terminal A'},
    {name: 'Eastwick'},
    {name: 'University City'},
    {name: '30th Street Station'},
    {name: 'Suburban Station'},
    {name: 'Jefferson Station'},
    {name: 'Temple University'},
  ],
  'Airport Line - Outbound': [
    {name: 'Temple University'},
    {name: 'Jefferson Station'},
    {name: 'Suburban Station'},
    {name: '30th Street Station'},
    {name: 'University City'},
    {name: 'Eastwick'},
    {name: 'Airport Terminal A'},
    {name: 'Airport Terminal B'},
    {name: 'Airport Terminal C D'},
    {name: 'Airport Terminal E F'},
  ],
  'Chestnut Hill East Line - Inbound': [
    {name: 'Chestnut Hill East'},
    {name: 'Gravers'},
    {name: 'Wyndmoor'},
    {name: 'Mount Airy'},
    {name: 'Sedgwick'},
    {name: 'Stenton'},
    {name: 'Washington Lane'},
    {name: 'Germantown'},
    {name: 'Wister'},
    {name: 'Wayne Junction'},
    {name: 'Temple University'},
    {name: 'Jefferson Station'},
    {name: 'Suburban Station'},
    {name: '30th Street Station'},
  ],
  'Chestnut Hill East Line - Outbound': [
    {name: '30th Street Station'},
    {name: 'Suburban Station'},
    {name: 'Jefferson Station'},
    {name: 'Temple University'},
    {name: 'Wayne Junction'},
    {name: 'Wister'},
    {name: 'Germantown'},
    {name: 'Washington Lane'},
    {name: 'Stenton'},
    {name: 'Sedgwick'},
    {name: 'Mount Airy'},
    {name: 'Wyndmoor'},
    {name: 'Gravers'},
    {name: 'Chestnut Hill East'},
  ],
  'Chestnut Hill West Line - Inbound': [
    {name: 'Chestnut Hill West'},
    {name: 'Highland'},
    {name: 'St. Martins'},
    {name: 'Allen Lane'},
    {name: 'Carpenter'},
    {name: 'Upsal'},
    {name: 'Tulpehocken'},
    {name: 'Chelten Avenue'},
    {name: 'Queen Lane'},
    {name: 'North Philadelphia'},
    {name: '30th Street Station'},
    {name: 'Suburban Station'},
    {name: 'Jefferson Station'},
    {name: 'Temple University'},
  ],
  'Chestnut Hill West Line - Outbound': [
    {name: 'Temple University'},
    {name: 'Jefferson Station'},
    {name: 'Suburban Station'},
    {name: '30th Street Station'},
    {name: 'North Philadelphia'},
    {name: 'Queen Lane'},
    {name: 'Chelten Avenue'},
    {name: 'Tulpehocken'},
    {name: 'Upsal'},
    {name: 'Carpenter'},
    {name: 'Allen Lane'},
    {name: 'St. Martins'},
    {name: 'Highland'},
    {name: 'Chestnut Hill West'},
  ],
  'Cynwyd Line - Inbound': [
    {name: 'Cynwyd'},
    {name: 'Bala'},
    {name: 'Wynnefield Avenue'},
    {name: '30th Street Station'},
    {name: 'Suburban Station'},
  ],
  'Cynwyd Line - Outbound': [
    {name: 'Suburban Station'},
    {name: '30th Street Station'},
    {name: 'Wynnefield Avenue'},
    {name: 'Bala'},
    {name: 'Cynwyd'},
  ],
  'Lansdale-Doylestown Line - Inbound': [
    {name: 'Doylestown'},
    {name: 'Delaware Valley College'},
    {name: 'New Britain'},
    {name: 'Chalfont'},
    {name: 'Link Belt'},
    {name: 'Colmar'},
    {name: 'Fortuna'},
    {name: 'Lansdale'},
    {name: 'Pennbrook'},
    {name: 'North Wales'},
    {name: 'Gwynedd Valley'},
    {name: 'Penllyn'},
    {name: 'Ambler'},
    {name: 'Fort Washington'},
    {name: 'Oreland'},
    {name: 'North Hills'},
    {name: 'Glenside'},
    {name: 'Jenkintown Wyncote'},
    {name: 'Elkins Park'},
    {name: 'Melrose Park'},
    {name: 'Fern Rock Transportation Ctr.'},
    {name: 'Wayne Junction'},
    {name: 'North Broad'},
    {name: 'Temple University'},
    {name: 'Jefferson Station'},
    {name: 'Suburban Station'},
    {name: '30th Street Station'},
  ],
  'Lansdale-Doylestown Line - Outbound': [
    {name: '30th Street Station'},
    {name: 'Suburban Station'},
    {name: 'Jefferson Station'},
    {name: 'Temple University'},
    {name: 'North Broad'},
    {name: 'Wayne Junction'},
    {name: 'Fern Rock Transportation Ctr.'},
    {name: 'Melrose Park'},
    {name: 'Elkins Park'},
    {name: 'Jenkintown Wyncote'},
    {name: 'Glenside'},
    {name: 'North Hills'},
    {name: 'Oreland'},
    {name: 'Fort Washington'},
    {name: 'Ambler'},
    {name: 'Penllyn'},
    {name: 'Gwynedd Valley'},
    {name: 'North Wales'},
    {name: 'Pennbrook'},
    {name: 'Lansdale'},
    {name: 'Fortuna'},
    {name: 'Colmar'},
    {name: 'Link Belt'},
    {name: 'Chalfont'},
    {name: 'New Britain'},
    {name: 'Delaware Valley College'},
    {name: 'Doylestown'},
  ],
  'Media-Elwyn Line - Inbound': [
    {name: 'Elwyn'},
    {name: 'Media'},
    {name: 'Moylan-Rose Valley'},
    {name: 'Wallingford'},
    {name: 'Swarthmore'},
    {name: 'Morton-Rutledge'},
    {name: 'Secane'},
    {name: 'Primos'},
    {name: 'Clifton-Aldan'},
    {name: 'Gladstone'},
    {name: 'Lansdowne'},
    {name: 'Fernwood-Yeadon'},
    {name: 'Angora'},
    {name: '49th Street'},
    {name: 'University City'},
    {name: '30th Street Station'},
    {name: 'Suburban Station'},
    {name: 'Jefferson Station'},
    {name: 'Temple University'},
  ],
  'Media-Elwyn Line - Outbound': [
    {name: 'Temple University'},
    {name: 'Jefferson Station'},
    {name: 'Suburban Station'},
    {name: '30th Street Station'},
    {name: 'University City'},
    {name: '49th Street'},
    {name: 'Angora'},
    {name: 'Fernwood-Yeadon'},
    {name: 'Lansdowne'},
    {name: 'Gladstone'},
    {name: 'Clifton-Aldan'},
    {name: 'Primos'},
    {name: 'Secane'},
    {name: 'Morton-Rutledge'},
    {name: 'Swarthmore'},
    {name: 'Wallingford'},
    {name: 'Moylan-Rose Valley'},
    {name: 'Media'},
    {name: 'Elwyn'},
  ],
  'Fox Chase Line - Inbound': [
    {name: 'Ryers'},
    {name: 'Cheltenham'},
    {name: 'Lawndale'},
    {name: 'Olney'},
    {name: 'Wayne Junction'},
    {name: 'Temple University'},
    {name: 'Jefferson Station'},
    {name: 'Suburban Station'},
    {name: '30th Street Station'},
  ],
  'Fox Chase Line - Outbound': [
    {name: '30th Street Station'},
    {name: 'Suburban Station'},
    {name: 'Jefferson Station'},
    {name: 'Temple University'},
    {name: 'Wayne Junction'},
    {name: 'Olney'},
    {name: 'Lawndale'},
    {name: 'Cheltenham'},
    {name: 'Ryers'},
    {name: 'Fox Chase'},
  ],
  'Wilmington-Newark Line - Inbound': [
    {name: 'Newark'},
    {name: 'Churchman\'s Crossing'},
    {name: 'Wilmington'},
    {name: 'Claymont'},
    {name: 'Marcus Hook'},
    {name: 'Highland Avenue'},
    {name: 'Chester'},
    {name: 'Eddystone'},
    {name: 'Crum Lynne'},
    {name: 'Ridley Park'},
    {name: 'Prospect Park - Moore'},
    {name: 'Norwood'},
    {name: 'Glenolden'},
    {name: 'Folcroft'},
    {name: 'Sharon Hill'},
    {name: 'Curtis Park'},
    {name: 'Darby'},
    {name: 'University City'},
    {name: '30th Street Station'},
    {name: 'Suburban Station'},
    {name: 'Jefferson Station'},
    {name: 'Temple University'},
  ],
  'Wilmington-Newark Line - Outbound': [
    {name: 'Temple University'},
    {name: 'Jefferson Station'},
    {name: 'Suburban Station'},
    {name: '30th Street Station'},
    {name: 'University City'},
    {name: 'Darby'},
    {name: 'Curtis Park'},
    {name: 'Sharon Hill'},
    {name: 'Folcroft'},
    {name: 'Glenolden'},
    {name: 'Norwood'},
    {name: 'Prospect Park - Moore'},
    {name: 'Ridley Park'},
    {name: 'Crum Lynne'},
    {name: 'Eddystone'},
    {name: 'Chester'},
    {name: 'Highland Avenue'},
    {name: 'Marcus Hook'},
    {name: 'Claymont'},
    {name: 'Wilmington'},
    {name: 'Churchman\'s Crossing'},
    {name: 'Newark'},
  ],
  'Manayunk-Norristown Line - Inbound': [
    {name: 'Norristown Elm Street'},
    {name: 'Main Street'},
    {name: 'Norristown T.C.'},
    {name: 'Conshohocken'},
    {name: 'Spring Mill'},
    {name: 'Miquon'},
    {name: 'Ivy Ridge'},
    {name: 'Manayunk'},
    {name: 'Wissahickon'},
    {name: 'East Falls'},
    {name: 'Allegheny'},
    {name: 'North Broad'},
    {name: 'Temple University'},
    {name: 'Jefferson Station'},
    {name: 'Suburban Station'},
    {name: '30th Street Station'},
  ],
  'Manayunk-Norristown Line - Outbound': [
    {name: '30th Street Station'},
    {name: 'Suburban Station'},
    {name: 'Jefferson Station'},
    {name: 'Temple University'},
    {name: 'North Broad'},
    {name: 'Allegheny'},
    {name: 'East Falls'},
    {name: 'Wissahickon'},
    {name: 'Manayunk'},
    {name: 'Ivy Ridge'},
    {name: 'Miquon'},
    {name: 'Spring Mill'},
    {name: 'Conshohocken'},
    {name: 'Norristown T.C.'},
    {name: 'Main Street'},
    {name: 'Norristown Elm Street'},
  ],
  'Paoli-Thorndale Line - Inbound': [
    {name: 'Thorndale'},
    {name: 'Downingtown'},
    {name: 'Whitford'},
    {name: 'Exton'},
    {name: 'Malvern'},
    {name: 'Paoli'},
    {name: 'Daylesford'},
    {name: 'Berwyn'},
    {name: 'Devon'},
    {name: 'Strafford'},
    {name: 'Wayne'},
    {name: 'St. Davids'},
    {name: 'Radnor'},
    {name: 'Villanova'},
    {name: 'Rosemont'},
    {name: 'Bryn Mawr'},
    {name: 'Haverford'},
    {name: 'Ardmore'},
    {name: 'Wynnewood'},
    {name: 'Narberth'},
    {name: 'Merion'},
    {name: 'Overbrook'},
    {name: '30th Street Station'},
    {name: 'Suburban Station'},
    {name: 'Jefferson Station'},
    {name: 'Temple University'},
  ],
  'Paoli-Thorndale Line - Outbound': [
    {name: 'Temple University'},
    {name: 'Jefferson Station'},
    {name: 'Suburban Station'},
    {name: '30th Street Station'},
    {name: 'Overbrook'},
    {name: 'Merion'},
    {name: 'Narberth'},
    {name: 'Wynnewood'},
    {name: 'Ardmore'},
    {name: 'Haverford'},
    {name: 'Bryn Mawr'},
    {name: 'Rosemont'},
    {name: 'Villanova'},
    {name: 'Radnor'},
    {name: 'St. Davids'},
    {name: 'Wayne'},
    {name: 'Strafford'},
    {name: 'Devon'},
    {name: 'Berwyn'},
    {name: 'Daylesford'},
    {name: 'Paoli'},
    {name: 'Malvern'},
    {name: 'Exton'},
    {name: 'Whitford'},
    {name: 'Downingtown'},
    {name: 'Thorndale'},
  ],
  'Trenton Line - Inbound': [
    {name: 'Trenton'},
    {name: 'Levittown-Tullytown'},
    {name: 'Bristol'},
    {name: 'Croydon'},
    {name: 'Eddington'},
    {name: 'Cornwells Heights'},
    {name: 'Torresdale'},
    {name: 'Holmesburg Jct'},
    {name: 'Tacony'},
    {name: 'Bridesburg'},
    {name: 'North Philadelphia'},
    {name: '30th Street Station'},
    {name: 'Suburban Station'},
    {name: 'Jefferson Station'},
    {name: 'Temple University'},
  ],
  'Trenton Line - Outbound': [
    {name: 'Temple University'},
    {name: 'Jefferson Station'},
    {name: 'Suburban Station'},
    {name: '30th Street Station'},
    {name: 'North Philadelphia'},
    {name: 'Bridesburg'},
    {name: 'Tacony'},
    {name: 'Holmesburg Jct'},
    {name: 'Torresdale'},
    {name: 'Cornwells Heights'},
    {name: 'Eddington'},
    {name: 'Croydon'},
    {name: 'Bristol'},
    {name: 'Levittown-Tullytown'},
    {name: 'Trenton'},
  ],
  'Warminster Line - Inbound': [
    {name: 'Warminster'},
    {name: 'Hatboro'},
    {name: 'Willow Grove'},
    {name: 'Crestmont'},
    {name: 'Roslyn'},
    {name: 'Ardsley'},
    {name: 'Glenside'},
    {name: 'Jenkintown Wyncote'},
    {name: 'Elkins Park'},
    {name: 'Melrose Park'},
    {name: 'Fern Rock Transportation Ctr.'},
    {name: 'Wayne Junction'},
    {name: 'Temple University'},
    {name: 'Jefferson Station'},
    {name: 'Suburban Station'},
    {name: '30th Street Station'},
    {name: 'University City'},
  ],
  'Warminster Line - Outbound': [
    {name: 'University City'},
    {name: '30th Street Station'},
    {name: 'Suburban Station'},
    {name: 'Jefferson Station'},
    {name: 'Temple University'},
    {name: 'Wayne Junction'},
    {name: 'Fern Rock Transportation Ctr.'},
    {name: 'Melrose Park'},
    {name: 'Elkins Park'},
    {name: 'Jenkintown Wyncote'},
    {name: 'Glenside'},
    {name: 'Ardsley'},
    {name: 'Roslyn'},
    {name: 'Crestmont'},
    {name: 'Willow Grove'},
    {name: 'Hatboro'},
    {name: 'Warminster'},
  ],
  'West Trenton Line - Inbound': [
    {name: 'West Trenton'},
    {name: 'Yardley'},
    {name: 'Woodbourne'},
    {name: 'Langhorne'},
    {name: 'Neshaminy'},
    {name: 'Trevose'},
    {name: 'Somerton'},
    {name: 'Forest Hills'},
    {name: 'Philmont'},
    {name: 'Bethayres'},
    {name: 'Meadowbrook'},
    {name: 'Rydal'},
    {name: 'Noble'},
    {name: 'Jenkintown Wyncote'},
    {name: 'Elkins Park'},
    {name: 'Melrose Park'},
    {name: 'Fern Rock Transportation Ctr.'},
    {name: 'Wayne Junction'},
    {name: 'Temple University'},
    {name: 'Jefferson Station'},
    {name: 'Suburban Station'},
    {name: '30th Street Station'},
    {name: 'University City'},
  ],
  'West Trenton Line - Outbound': [
    {name: 'University City'},
    {name: '30th Street Station'},
    {name: 'Suburban Station'},
    {name: 'Jefferson Station'},
    {name: 'Temple University'},
    {name: 'Wayne Junction'},
    {name: 'Fern Rock Transportation Ctr.'},
    {name: 'Melrose Park'},
    {name: 'Elkins Park'},
    {name: 'Jenkintown Wyncote'},
    {name: 'Noble'},
    {name: 'Rydal'},
    {name: 'Meadowbrook'},
    {name: 'Bethayres'},
    {name: 'Philmont'},
    {name: 'Forest Hills'},
    {name: 'Somerton'},
    {name: 'Trevose'},
    {name: 'Neshaminy'},
    {name: 'Langhorne'},
    {name: 'Woodbourne'},
    {name: 'Yardley'},
    {name: 'West Trenton'},
  ],
  'Norristown High Speed Line - Inbound': [
    {name: 'Norristown Transportation Ctr.'},
    {name: 'Bridgeport'},
    {name: 'DeKalb Street'},
    {name: 'Hughes Park'},
    {name: 'Gulph Mills'},
    {name: 'Matsonford'},
    {name: 'County Line'},
    {name: 'Radnor'},
    {name: 'Villanova'},
    {name: 'Stadium–Ithan Avenue'},
    {name: 'Garrett Hill'},
    {name: 'Roberts Road'},
    {name: 'Bryn Mawr'},
    {name: 'Haverford'},
    {name: 'Ardmore Avenue'},
    {name: 'Ardmore Junction'},
    {name: 'Wynnewood Road'},
    {name: 'Beechwood-Brookline'},
    {name: 'Penfield'},
    {name: 'Township Line Road'},
    {name: 'Parkview'},
    {name: '69th Street Transportation Ctr.'}
  ],
  'Norristown High Speed Line - Outbound': [
    {name: '69th Street Transportation Ctr.'},
    {name: 'Parkview'},
    {name: 'Township Line Road'},
    {name: 'Penfield'},
    {name: 'Beechwood-Brookline'},
    {name: 'Wynnewood Road'},
    {name: 'Ardmore Junction'},
    {name: 'Ardmore Avenue'},
    {name: 'Haverford'},
    {name: 'Bryn Mawr'},
    {name: 'Roberts Road'},
    {name: 'Garrett Hill'},
    {name: 'Stadium–Ithan Avenue'},
    {name: 'Villanova'},
    {name: 'Radnor'},
    {name: 'County Line'},
    {name: 'Matsonford'},
    {name: 'Gulph Mills'},
    {name: 'Hughes Park'},
    {name: 'DeKalb Street'},
    {name: 'Bridgeport'},
    {name: 'Norristown Transportation Ctr.'}
  ]
};

getStations = function(){
  return stations;
}